# Generated by Django 3.0 on 2019-12-14 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artits_name', models.CharField(max_length=101)),
                ('artist_desc', models.TextField(verbose_name='About artits')),
            ],
        ),
        migrations.CreateModel(
            name='Good',
            fields=[
                ('good_id', models.AutoField(primary_key=True, serialize=False)),
                ('good_title', models.CharField(max_length=200, unique=True, verbose_name='Product Name')),
                ('good_description', models.TextField()),
                ('good_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('good_pic', models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='pic_folder/')),
            ],
        ),
        migrations.CreateModel(
            name='PictureModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_pic', models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='pic_folder/')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('ph_NUMBER', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id_basket', models.AutoField(primary_key=True, serialize=False)),
                ('count', models.PositiveIntegerField(default=0)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('c_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='artshop.User')),
            ],
        ),
    ]
