# Generated by Django 3.0 on 2019-12-14 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artshop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='ph_NUMBER',
            new_name='ph_number',
        ),
        migrations.AlterField(
            model_name='picturemodel',
            name='work_pic',
            field=models.FileField(blank=True, upload_to='pic_folder/'),
        ),
    ]
